require('./bootstrap');

window.Vue = require('vue');
var VueRouter = require('vue-router');
Vue.use(VueRouter);
var api = window.axios.create({ headers: { Accept: 'application/json' } });

var Home = {
  data: function () { return { innovations: [], loading: true }; },
  created: function () { var vm = this; api.get('/api/spa/innovations').then(function (r) { vm.innovations = r.data.data; }).finally(function () { vm.loading = false; }); },
  template: '<main class="container py-5"><section class="jumbotron bg-white shadow-sm"><h1>Krenova</h1><p class="lead">Kreativitas dan inovasi masyarakat Salatiga.</p><router-link to="/dashboard" class="btn btn-primary">Dashboard</router-link></section><h2 class="h4">Inovasi terbaru</h2><p v-if="loading">Memuat…</p><div v-else class="row"><div v-for="item in innovations" :key="item.id" class="col-md-4 mb-3"><article class="card h-100"><div class="card-body"><h3 class="h5">{{ item.nama_inovasi }}</h3><p class="text-muted mb-0">{{ item.tahap_inovasi || \'Dalam pengembangan\' }}</p></div></article></div><p v-if="!innovations.length" class="col-12 text-muted">Belum ada inovasi.</p></div></main>'
};
var Dashboard = {
  data: function () { return { me: null, loading: true }; },
  created: function () { var vm = this; api.get('/api/spa/me').then(function (r) { vm.me = r.data; }).finally(function () { vm.loading = false; }); },
  template: '<main class="container py-5"><h1 class="h3">Dashboard</h1><p v-if="loading">Memuat…</p><div v-else-if="me.authenticated" class="card card-body">Selamat datang, <strong>{{ me.user.nama || me.user.email }}</strong>. <router-link to="/inventor" class="btn btn-primary mt-3">Profil inventor</router-link></div><div v-else class="alert alert-info">Silakan <a href="/login">masuk dengan Google</a> untuk mengelola data.</div></main>'
};
var Inventor = {
  data: function () { return { form: {}, options: { kategori: [], tipe: [], kecamatan: [], kelurahan: [] }, loading: true, saving: false, message: '', errors: {} }; },
  created: function () { var vm = this; Promise.all([api.get('/api/spa/options'), api.get('/api/spa/inventor')]).then(function (r) { vm.options = r[0].data; vm.form = r[1].data || {}; if (vm.form.id_kec) vm.kelurahan(); }).catch(function (e) { if (e.response && e.response.status === 401) vm.$router.push('/dashboard'); }).finally(function () { vm.loading = false; }); },
  methods: { kelurahan: function () { var vm = this; if (vm.form.id_kec) api.get('/api/spa/kelurahan/' + vm.form.id_kec).then(function (r) { vm.options.kelurahan = r.data; }); }, save: function () { var vm = this; vm.saving = true; vm.errors = {}; api.put('/api/spa/inventor', vm.form).then(function (r) { vm.form = r.data.data; vm.message = r.data.message; }).catch(function (e) { vm.errors = (e.response && e.response.data.errors) || {}; }).finally(function () { vm.saving = false; }); } },
  template: '<main class="container py-5"><h1 class="h3">Profil inventor</h1><p v-if="loading">Memuat…</p><form v-else @submit.prevent="save" class="card card-body"><div v-if="message" class="alert alert-success">{{ message }}</div><div class="form-row"><div class="form-group col-md-6"><label>Kategori</label><select v-model="form.kategori" class="form-control" required><option value="">Pilih kategori</option><option v-for="x in options.kategori" :value="x.id">{{ x.nama }}</option></select><small class="text-danger">{{ errors.kategori && errors.kategori[0] }}</small></div><div class="form-group col-md-6"><label>Tipe</label><select v-model="form.tipe" class="form-control" required><option value="">Pilih tipe</option><option v-for="x in options.tipe" :value="x.id">{{ x.tipe }}</option></select></div></div><div class="form-row"><div class="form-group col-md-6"><label>Nama perorangan</label><input v-model="form.p_nama" class="form-control"></div><div class="form-group col-md-6"><label>Nama kelompok</label><input v-model="form.k_nama" class="form-control"></div></div><div class="form-row"><div class="form-group col-md-6"><label>Telepon</label><input v-model="form.telepon" class="form-control" required><small class="text-danger">{{ errors.telepon && errors.telepon[0] }}</small></div><div class="form-group col-md-6"><label>Alamat</label><input v-model="form.alamat" class="form-control" required></div></div><div class="form-row"><div class="form-group col-md-6"><label>Kecamatan</label><select v-model="form.id_kec" @change="form.id_kel = null; kelurahan()" class="form-control" required><option value="">Pilih kecamatan</option><option v-for="x in options.kecamatan" :value="x.id">{{ x.nama_kec }}</option></select></div><div class="form-group col-md-6"><label>Kelurahan</label><select v-model="form.id_kel" class="form-control" required><option value="">Pilih kelurahan</option><option v-for="x in options.kelurahan" :value="x.id">{{ x.nama_kel }}</option></select></div></div><button :disabled="saving" class="btn btn-primary align-self-start">{{ saving ? \'Menyimpan…\' : \'Simpan profil\' }}</button></form></main>'
};
var Shell = { template: '<div><nav class="navbar navbar-expand navbar-dark bg-primary"><router-link class="navbar-brand" to="/">Krenova</router-link><div class="navbar-nav"><router-link class="nav-link" to="/dashboard">Dashboard</router-link><router-link class="nav-link" to="/inventor">Inventor</router-link></div></nav><router-view></router-view></div>' };
var router = new VueRouter({ mode: 'history', routes: [{ path: '/', component: Home }, { path: '/dashboard', component: Dashboard }, { path: '/inventor', component: Inventor }, { path: '*', redirect: '/' }] });
new Vue({ el: '#app', router: router, render: function (h) { return h(Shell); } });